[tool.poetry]
name = "botw"
version = "0.1.0"
description = ""
authors = ["Andrew Herbig <notandrewherbig@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.15.5"
toml = "^0.10.1"

[tool.poetry.dev-dependencies]
isort = "^5.5.4"
black = "^20.8b1"
pre-commit = "^2.7.1"
flake8 = "^3.8.4"
pyupgrade = "^2.7.2"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
